# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups_amazon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ups_amazon.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10ups_amazon.proto\",\n\tInitWorld\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"9\n\rWarehouseInfo\x12\x0c\n\x04whid\x18\x01 \x02(\x05\x12\x0c\n\x04wh_x\x18\x02 \x02(\x05\x12\x0c\n\x04wh_y\x18\x03 \x02(\x05\"H\n\x12\x44\x65termineWarehouse\x12\"\n\nwarehouses\x18\x01 \x03(\x0b\x32\x0e.WarehouseInfo\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"G\n\x0e\x44\x65termineTruck\x12%\n\rarrivedtrucks\x18\x01 \x03(\x0b\x32\x0e.TruckLocation\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\".\n\rTruckLocation\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0c\n\x04whid\x18\x02 \x02(\x05\"@\n\x0c\x44\x65termineDst\x12 \n\rleavingtrucks\x18\x01 \x03(\x0b\x32\t.TruckDst\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"A\n\x08TruckDst\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\x12\x0e\n\x06shipid\x18\x04 \x02(\x03\"@\n\x0eSettleShipment\x12\x1e\n\x08packages\x18\x01 \x03(\x0b\x32\x0c.PackageInfo\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"T\n\x0bPackageInfo\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\x12\x0e\n\x06shipid\x18\x04 \x02(\x03\"m\n\nUACommands\x12\x1a\n\x06worlds\x18\x01 \x03(\x0b\x32\n.InitWorld\x12\x1f\n\x06trucks\x18\x02 \x03(\x0b\x32\x0f.DetermineTruck\x12\"\n\tshipments\x18\x03 \x03(\x0b\x32\x0f.SettleShipment\"S\n\nAUCommands\x12\'\n\nwarehouses\x18\x01 \x03(\x0b\x32\x13.DetermineWarehouse\x12\x1c\n\x05\x64\x65sts\x18\x02 \x03(\x0b\x32\r.DetermineDst\"+\n\x08Response\x12\x0f\n\x07succeed\x18\x01 \x02(\x08\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03')
)




_INITWORLD = _descriptor.Descriptor(
  name='InitWorld',
  full_name='InitWorld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='InitWorld.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='InitWorld.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=64,
)


_WAREHOUSEINFO = _descriptor.Descriptor(
  name='WarehouseInfo',
  full_name='WarehouseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whid', full_name='WarehouseInfo.whid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wh_x', full_name='WarehouseInfo.wh_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wh_y', full_name='WarehouseInfo.wh_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=123,
)


_DETERMINEWAREHOUSE = _descriptor.Descriptor(
  name='DetermineWarehouse',
  full_name='DetermineWarehouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouses', full_name='DetermineWarehouse.warehouses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='DetermineWarehouse.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=197,
)


_DETERMINETRUCK = _descriptor.Descriptor(
  name='DetermineTruck',
  full_name='DetermineTruck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrivedtrucks', full_name='DetermineTruck.arrivedtrucks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='DetermineTruck.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=270,
)


_TRUCKLOCATION = _descriptor.Descriptor(
  name='TruckLocation',
  full_name='TruckLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='TruckLocation.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whid', full_name='TruckLocation.whid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=318,
)


_DETERMINEDST = _descriptor.Descriptor(
  name='DetermineDst',
  full_name='DetermineDst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leavingtrucks', full_name='DetermineDst.leavingtrucks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='DetermineDst.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=384,
)


_TRUCKDST = _descriptor.Descriptor(
  name='TruckDst',
  full_name='TruckDst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='TruckDst.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='TruckDst.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='TruckDst.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shipid', full_name='TruckDst.shipid', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=451,
)


_SETTLESHIPMENT = _descriptor.Descriptor(
  name='SettleShipment',
  full_name='SettleShipment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packages', full_name='SettleShipment.packages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='SettleShipment.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=517,
)


_PACKAGEINFO = _descriptor.Descriptor(
  name='PackageInfo',
  full_name='PackageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='PackageInfo.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='PackageInfo.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='PackageInfo.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shipid', full_name='PackageInfo.shipid', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=603,
)


_UACOMMANDS = _descriptor.Descriptor(
  name='UACommands',
  full_name='UACommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worlds', full_name='UACommands.worlds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trucks', full_name='UACommands.trucks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shipments', full_name='UACommands.shipments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=714,
)


_AUCOMMANDS = _descriptor.Descriptor(
  name='AUCommands',
  full_name='AUCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouses', full_name='AUCommands.warehouses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dests', full_name='AUCommands.dests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=799,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeed', full_name='Response.succeed', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='Response.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=801,
  serialized_end=844,
)

_DETERMINEWAREHOUSE.fields_by_name['warehouses'].message_type = _WAREHOUSEINFO
_DETERMINETRUCK.fields_by_name['arrivedtrucks'].message_type = _TRUCKLOCATION
_DETERMINEDST.fields_by_name['leavingtrucks'].message_type = _TRUCKDST
_SETTLESHIPMENT.fields_by_name['packages'].message_type = _PACKAGEINFO
_UACOMMANDS.fields_by_name['worlds'].message_type = _INITWORLD
_UACOMMANDS.fields_by_name['trucks'].message_type = _DETERMINETRUCK
_UACOMMANDS.fields_by_name['shipments'].message_type = _SETTLESHIPMENT
_AUCOMMANDS.fields_by_name['warehouses'].message_type = _DETERMINEWAREHOUSE
_AUCOMMANDS.fields_by_name['dests'].message_type = _DETERMINEDST
DESCRIPTOR.message_types_by_name['InitWorld'] = _INITWORLD
DESCRIPTOR.message_types_by_name['WarehouseInfo'] = _WAREHOUSEINFO
DESCRIPTOR.message_types_by_name['DetermineWarehouse'] = _DETERMINEWAREHOUSE
DESCRIPTOR.message_types_by_name['DetermineTruck'] = _DETERMINETRUCK
DESCRIPTOR.message_types_by_name['TruckLocation'] = _TRUCKLOCATION
DESCRIPTOR.message_types_by_name['DetermineDst'] = _DETERMINEDST
DESCRIPTOR.message_types_by_name['TruckDst'] = _TRUCKDST
DESCRIPTOR.message_types_by_name['SettleShipment'] = _SETTLESHIPMENT
DESCRIPTOR.message_types_by_name['PackageInfo'] = _PACKAGEINFO
DESCRIPTOR.message_types_by_name['UACommands'] = _UACOMMANDS
DESCRIPTOR.message_types_by_name['AUCommands'] = _AUCOMMANDS
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitWorld = _reflection.GeneratedProtocolMessageType('InitWorld', (_message.Message,), dict(
  DESCRIPTOR = _INITWORLD,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:InitWorld)
  ))
_sym_db.RegisterMessage(InitWorld)

WarehouseInfo = _reflection.GeneratedProtocolMessageType('WarehouseInfo', (_message.Message,), dict(
  DESCRIPTOR = _WAREHOUSEINFO,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:WarehouseInfo)
  ))
_sym_db.RegisterMessage(WarehouseInfo)

DetermineWarehouse = _reflection.GeneratedProtocolMessageType('DetermineWarehouse', (_message.Message,), dict(
  DESCRIPTOR = _DETERMINEWAREHOUSE,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:DetermineWarehouse)
  ))
_sym_db.RegisterMessage(DetermineWarehouse)

DetermineTruck = _reflection.GeneratedProtocolMessageType('DetermineTruck', (_message.Message,), dict(
  DESCRIPTOR = _DETERMINETRUCK,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:DetermineTruck)
  ))
_sym_db.RegisterMessage(DetermineTruck)

TruckLocation = _reflection.GeneratedProtocolMessageType('TruckLocation', (_message.Message,), dict(
  DESCRIPTOR = _TRUCKLOCATION,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:TruckLocation)
  ))
_sym_db.RegisterMessage(TruckLocation)

DetermineDst = _reflection.GeneratedProtocolMessageType('DetermineDst', (_message.Message,), dict(
  DESCRIPTOR = _DETERMINEDST,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:DetermineDst)
  ))
_sym_db.RegisterMessage(DetermineDst)

TruckDst = _reflection.GeneratedProtocolMessageType('TruckDst', (_message.Message,), dict(
  DESCRIPTOR = _TRUCKDST,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:TruckDst)
  ))
_sym_db.RegisterMessage(TruckDst)

SettleShipment = _reflection.GeneratedProtocolMessageType('SettleShipment', (_message.Message,), dict(
  DESCRIPTOR = _SETTLESHIPMENT,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:SettleShipment)
  ))
_sym_db.RegisterMessage(SettleShipment)

PackageInfo = _reflection.GeneratedProtocolMessageType('PackageInfo', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGEINFO,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:PackageInfo)
  ))
_sym_db.RegisterMessage(PackageInfo)

UACommands = _reflection.GeneratedProtocolMessageType('UACommands', (_message.Message,), dict(
  DESCRIPTOR = _UACOMMANDS,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UACommands)
  ))
_sym_db.RegisterMessage(UACommands)

AUCommands = _reflection.GeneratedProtocolMessageType('AUCommands', (_message.Message,), dict(
  DESCRIPTOR = _AUCOMMANDS,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AUCommands)
  ))
_sym_db.RegisterMessage(AUCommands)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
