# Generated by Django 2.2 on 2019-04-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190422_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='truck',
        ),
        migrations.AddField(
            model_name='package',
            name='truckid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_set', to='myapp.truck'),
        ),
    ]
