# Generated by Django 2.2 on 2019-04-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190422_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='truckid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
