# Generated by Django 2.2 on 2019-04-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190422_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Destination_Y',
            new_name='destination_Y',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Destination_X',
        ),
        migrations.AddField(
            model_name='package',
            name='destination_X',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
