# Generated by Django 2.2 on 2019-04-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190422_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_id',
            field=models.BigIntegerField(),
        ),
    ]
