# Generated by Django 2.2 on 2019-04-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190422_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination_x',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_y',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
