# Generated by Django 2.2 on 2019-04-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='query',
        ),
    ]
