# Generated by Django 2.2 on 2019-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_y',
            field=models.IntegerField(null=True),
        ),
    ]
