# Generated by Django 2.2 on 2019-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20190423_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
