# Generated by Django 2.2 on 2019-04-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_package_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.BigIntegerField()),
                ('satisfied', models.CharField(blank=True, max_length=1, null=True)),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
