# Generated by Django 2.2 on 2019-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.CharField(default=0, max_length=50, verbose_name='Address'),
        ),
    ]
