# Generated by Django 2.2 on 2019-04-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190420_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=20)),
                ('truck_status', models.SmallIntegerField(choices=[(1, 'idle'), (2, 'en route to a warehouse'), (3, 'invalid'), (4, 'delivering'), (5, 'waiting for pickup')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_set', to='myapp.Truck'),
        ),
    ]
