# Generated by Django 2.2 on 2019-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190421_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Destination',
        ),
        migrations.AddField(
            model_name='package',
            name='Destination_X',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='Destination_Y',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
