# Generated by Django 2.2 on 2019-04-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190422_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='destination_x',
            new_name='Destination_X',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='destination_y',
            new_name='Destination_Y',
        ),
    ]
