# Generated by Django 2.2 on 2019-04-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190422_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='truckid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_id',
            field=models.IntegerField(),
        ),
    ]
