# Generated by Django 2.2 on 2019-04-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190422_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_status',
            field=models.SmallIntegerField(choices=[(1, 'idle'), (2, 'traveling'), (3, 'arrive warehouse'), (4, 'loading'), (5, 'delivering')], default=1),
        ),
    ]
